// DO NOT EDIT THIS FILE! IT IS AUTOMATICALLY GENERATED FROM FILE "src/Lexer.gold"
import gold.structures.automaton.*;
import gold.util.*;
import gold.visualization.automaton.*;
import java.lang.*;
import org.apfloat.*;
import static gold.util.GReflection.*;
@SuppressWarnings("all")
public final class Lexer {
  static {
    gold.swing.util.GUtilities.installGoldLookAndFeel();
  }
  public static void main(String[] args) {
    int $line=0;
    Object $result=null;
    $try:try {
      $line=5;
      Object lexer=$fix(Lexer.createTransducer());
      $line=6;
      Lexer.testLexer($cast(gold.structures.automaton.ITransducer.class,lexer));
    }
    catch (Throwable $throwable) {
      $rethrow($throwable,Lexer.class,"main",$line);
    }
  }
  public static Object testLexer(ITransducer M) {
    int $line=0;
    Object $result=null;
    $try:try {
      $line=12;
      java.util.Scanner sc=null;
      sc=$invokeConstructor(java.util.Scanner.class,new Object[]{$invokeField(System.class,"in",true,null)});
      $line=13;
      while (true) {
        if (!($bool(true))) break;
        $line=14;
        System.out.println($message(new Object[]{"----------------------------"}));
        $line=15;
        System.out.println($message(new Object[]{"Enter an input string: "}));
        $line=16;
        Object string=$fix($opAdditY(((java.util.Scanner)sc).nextLine()," "));
        $line=17;
        Object result=$fix(((gold.structures.automaton.ITransducer)M).acceptsString($cast(java.lang.String.class,string)));
        $line=18;
        Object tokenStream=$fix(((gold.structures.automaton.ITransducer)M).getOutputString());
        $line=19;
        System.out.println($message(new Object[]{$opAdditY($opAdditY("The lexer did ",(($bool(result))?(""):("not ")))," accept the string.")}));
        $line=20;
        if ($bool(result)) {
          $line=20;
          System.out.println($message(new Object[]{$opAdditY("Token Stream: ",tokenStream)}));
        }
      }
    }
    catch (Throwable $throwable) {
      $rethrow($throwable,Lexer.class,"testLexer",$line);
    }
    return $result;
  }
  public static Object names=null;
  public static ITransducer createTransducer() {
    int $line=0;
    Object $result=null;
    $try:try {
      $line=34;
      Object preKW=$fix(GCollections.asSet("p","pl","plu","plus","t","ti","tim","time","times"));
      $line=35;
      Object Q=$fix(GCollections.asSet("I","Id","p","pl","plu","plus","t","ti","tim","time","times","Num","Err"));
      $line=37;
      Object \u03A3=$fix($opUnionY($opUnionY($opIntvlY('0','9'),$opIntvlY('a','z')),GCollections.asSet('(',')',' ')));
      $line=38;
      Object Out=$fix(GCollections.asSet('(',')','+','*','v','n'));
      $line=39;
      Object q_0=$fix("I");
      $line=40;
      Object F=$fix(GCollections.asSet("I"));
      $line=41;
      $result=$invokeConstructor(GDeterministicTransducer.class,new Object[]{Q,\u03A3,Out,q_0,F,new GMethod(Lexer.class,"\u03B4"),new GMethod(Lexer.class,"g"),new GMethod(Lexer.class,"h")});
      if (true) break $try;
      $line=42;
      $rethrow(new RuntimeException("The function \"createTransducer()\" did not return a value."));
    }
    catch (Throwable $throwable) {
      $rethrow($throwable,Lexer.class,"createTransducer",$line);
    }
    return $cast(ITransducer.class,$result);
  }
  public static Object \u03B4(Object q, Object \u03C3) {
    int $line=0;
    Object $result=null;
    $try:try {
      $line=45;
      if ($bool($opEqualY(q,"Err"))) {
        $line=45;
        $result="Err";
        if (true) break $try;
      }
      else {
        $line=46;
        if ($opMembrY(\u03C3,GCollections.asSet('(',')',' '))) {
          $line=46;
          $result="I";
          if (true) break $try;
        }
        else {
          $line=47;
          if (($opEqualY(q,"I")&&$opEqualY(\u03C3,'p'))) {
            $line=47;
            $result="p";
            if (true) break $try;
          }
          else {
            $line=48;
            if (($opEqualY(q,"I")&&$opEqualY(\u03C3,'t'))) {
              $line=48;
              $result="t";
              if (true) break $try;
            }
            else {
              $line=49;
              if (($opEqualY(q,"I")&&$opMembrY(\u03C3,$opIntvlY('0','9')))) {
                $line=49;
                $result="Num";
                if (true) break $try;
              }
              else {
                $line=50;
                if (($opEqualY(q,"Num")&&$opMembrY(\u03C3,$opIntvlY('0','9')))) {
                  $line=50;
                  $result="Num";
                  if (true) break $try;
                }
                else {
                  $line=51;
                  if (($opEqualY(q,"Num")&&$opMembrY(\u03C3,$opIntvlY('a','z')))) {
                    $line=51;
                    $result="Err";
                    if (true) break $try;
                  }
                  else {
                    $line=53;
                    if (($opEqualY(q,"p")&&$opEqualY(\u03C3,'l'))) {
                      $line=53;
                      $result="pl";
                      if (true) break $try;
                    }
                    else {
                      $line=54;
                      if (($opEqualY(q,"pl")&&$opEqualY(\u03C3,'u'))) {
                        $line=54;
                        $result="plu";
                        if (true) break $try;
                      }
                      else {
                        $line=55;
                        if (($opEqualY(q,"plu")&&$opEqualY(\u03C3,'s'))) {
                          $line=55;
                          $result="plus";
                          if (true) break $try;
                        }
                        else {
                          $line=56;
                          if (($opEqualY(q,"t")&&$opEqualY(\u03C3,'i'))) {
                            $line=56;
                            $result="ti";
                            if (true) break $try;
                          }
                          else {
                            $line=57;
                            if (($opEqualY(q,"ti")&&$opEqualY(\u03C3,'m'))) {
                              $line=57;
                              $result="tim";
                              if (true) break $try;
                            }
                            else {
                              $line=58;
                              if (($opEqualY(q,"tim")&&$opEqualY(\u03C3,'e'))) {
                                $line=58;
                                $result="time";
                                if (true) break $try;
                              }
                              else {
                                $line=59;
                                if (($opEqualY(q,"time")&&$opEqualY(\u03C3,'s'))) {
                                  $line=59;
                                  $result="times";
                                  if (true) break $try;
                                }
                                else {
                                  $line=62;
                                  $result="Id";
                                  if (true) break $try;
                                }
                              }
                            }
                          }
                        }
                      }
                    }
                  }
                }
              }
            }
          }
        }
      }
      $line=64;
      $rethrow(new RuntimeException("The function \"\u03B4(q:Object,\u03C3:Object)\" did not return a value."));
    }
    catch (Throwable $throwable) {
      $rethrow($throwable,Lexer.class,"\u03B4",$line);
    }
    return $result;
  }
  public static Object g(Object q) {
    int $line=0;
    Object $result=null;
    $try:try {
      $line=69;
      $result="";
      if (true) break $try;
      $line=70;
      $rethrow(new RuntimeException("The function \"g(q:Object)\" did not return a value."));
    }
    catch (Throwable $throwable) {
      $rethrow($throwable,Lexer.class,"g",$line);
    }
    return $result;
  }
  public static Object h(Object q, Object \u03C3) {
    int $line=0;
    Object $result=null;
    $try:try {
      $line=73;
      String s=null;
      s=$defaultValue(String.class);
      $line=74;
      s=$cast(String.class,$fix(""));
      $line=76;
      if ((!$opMembrY(q,GCollections.asSet("Err"))&&$opMembrY(\u03C3,GCollections.asSet('(',')',' ')))) {
        $line=77;
        if (!$opMembrY(\u03C3,GCollections.asSet(' '))) {
          $line=77;
          s=$cast(String.class,$fix($invokeMethod(String.class,"valueOf",true,null,new Object[]{\u03C3})));
        }
        $line=78;
        if ($opEqualY(q,"I")) {
          $line=78;
          $result=s;
          if (true) break $try;
        }
        else {
          $line=79;
          if ($opEqualY(q,"plus")) {
            $line=79;
            $result=$opAdditY("+",s);
            if (true) break $try;
          }
          else {
            $line=80;
            if ($opEqualY(q,"times")) {
              $line=80;
              $result=$opAdditY("*",s);
              if (true) break $try;
            }
            else {
              $line=81;
              if ($opEqualY(q,"Num")) {
                $line=81;
                $result=$opAdditY("n",s);
                if (true) break $try;
              }
              else {
                $line=82;
                $result=$opAdditY("v",s);
                if (true) break $try;
              }
            }
          }
        }
      }
      else {
        $line=84;
        $result="";
        if (true) break $try;
      }
      $line=86;
      $rethrow(new RuntimeException("The function \"h(q:Object,\u03C3:Object)\" did not return a value."));
    }
    catch (Throwable $throwable) {
      $rethrow($throwable,Lexer.class,"h",$line);
    }
    return $result;
  }
}
